### PR TITLE
Initial cleanup with static analysis tools:  whitespace, idiom, deleting unused items

### PR DESCRIPTION
**Pull request by tschady**
Many changes here using static analysis tools to find style and linting errors (kibit, eastwood, cljfmt) to conform to community standards.

It might be easiest to review each commit in turn, since the first one changes almost every line (whitespace corrections according to bbatsov's community style guide).

### CODE REVIEW

**Comment by maoo** [comment]
This is great @tschady , thanks a lot!

I've rebased the PR against the `dev` branch, but I see a conflict that I'm not 100% sure how to resolve; could you please have a look at it?

Also, I wonder how we can prevent linting issues in the future; I believe that Travis builds should fail, if linting is broken; do you know how we can update our `.travis.yml` accordingly?

TY!

**Comment by tschady** [comment]
@maoo I cannot easily resolve the conflict as I don't have write perms, but the only diff is version number bumps in dev branch.  Updating those will resolve.  Want to give it a try?  I'll work off dev for the future.

**Comment by tschady** [comment]
> Also, I wonder how we can prevent linting issues in the future; I believe that Travis builds should fail, if linting is broken; do you know how we can update our `.travis.yml` accordingly?

Added #43

**Comment by maoo** [comment]
LGTM, merging.

**Pull request merged**
